### ISSUE TITLE
conversion in creation of SArray

### ISSUE THREAD

**Issue by KristofferC** [andyferris/StaticArrays.jl#13]
This could be made to work  by calling convert on each element in the input vector.

```jl
SVector{5, Float32}(rand(Float64, 5))
```

**Comment by andyferris** [comment]
Hmm... I thought I had this one covered... I'll fix that. BTW, `convert` works fine.

**Comment by andyferris** [comment]
Right, I found what was missing. That was on my mental to-do list some time ago, but I guess I never got around to it!
