### ISSUE TITLE
rand with an SArray as eltype

### ISSUE THREAD

**Issue by KristofferC** [andyferris/StaticArrays.jl#14]
Sorry for spamming issues.

It would be nice if this could work `rand(SVector{5, Float64}, 5)`

I guess it should be enough to implement `rand(::RNG, ::SArray)`.

**Comment by andyferris** [comment]
Hmmm.... there is a certain logic to that. Perhaps changing my `rand()` signatures will be sufficient.

**Comment by andyferris** [comment]
Just to clarify, you want a `Vector` of 5 `SVector{5, Float64}`'s, right?

**Comment by andyferris** [comment]
Now we have this:
```
julia> rand(SVector{3}, 6)
6-element Array{StaticArrays.SVector{3,T},1}:
 [0.458227,0.344626,0.396484]
 [0.809879,0.267388,0.335738]
 [0.993943,0.613799,0.743661]
 [0.943414,0.998016,0.881938]
 [0.531196,0.720806,0.440227]
 [0.565579,0.389288,0.264825]
```

**Comment by KristofferC** [comment]
Exactly, thanks.

**Comment by andyferris** [comment]
No worries. It is also tagged, now.
