### ISSUE TITLE
Mistake in ctranspose?

### ISSUE THREAD

**Issue by tkoolen** [andyferris/StaticArrays.jl#5]
Hi, just trying out your package. So far so good, except for this. I'm getting:
```
ERROR: UndefVarError: v not defined
 in ctranspose(...) at <dir>/packages/v0.5/StaticArrays/src/linalg.jl:77
 in macro expansion at <dir>/packages/v0.5/StaticArrays/src/matrix_multiply.jl:20 [inlined]
 in Ac_mul_B(::StaticArrays.SMatrix{3,5,Float64,15}, ::StaticArrays.SVector{3,Float64}) at <dir>/packages/v0.5/StaticArrays/src/matrix_multiply.jl:18
```

See here:
https://github.com/andyferris/StaticArrays.jl/blob/master/src/linalg.jl#L77

You probably just meant to use `m` instead of `v`?

**Comment by tkoolen** [comment]
Same in `transpose`, it seems.

**Comment by andyferris** [comment]
Oh, oops! Thanks for catching this. :) 

More tests needed...

**Comment by andyferris** [comment]
Should now be fixed on master. I'll try make a tag.

**Comment by tkoolen** [comment]
Great, thanks!
