### ISSUE TITLE
zeros function: inconsistent output type

### ISSUE THREAD

**Issue by tkoolen** [andyferris/StaticArrays.jl#6]
I'll be reporting a bunch of issues I found while switching over some of my code from FixedSizeArrays to StaticArrays. Here's the first.

Consider the following use of `zeros`:
```julia
x = zeros(SMatrix{3, 1, Float64})
zeros(x)
```
Currently, the output is:
```julia
3×1 StaticArrays.MMatrix{3,1,Float64,3}:
 0.0
 0.0
 0.0
```
I would expect the output to be of type `SMatrix`, not `MMatrix`.

**Comment by andyferris** [comment]
I've never tried calling zeros on an `AbstractArray` before... interesting. Like many functions, this falls back to the definition in base, which either gives you a mutable static array or simply `Array`. You can easily do `zeros(typeof(x))` above. I'll try get around to fixing this.
