### ISSUE TITLE
Support for (n x 0) * (0 x m) products

### ISSUE THREAD

**Issue by tkoolen** [andyferris/StaticArrays.jl#8]
This is not a critical feature, but a very-nice-to-have, as it gets rid of the need for lots of special cases in user code.
Plain arrays support the following:
```julia
m1 = zeros(3, 0)
m2 = zeros(0, 3)
v = zeros(0)
m1 * m2
m2 * m1
m1 * v
```
Currently, StaticArrays doesn't:
```julia
m1 = zeros(SMatrix{3, 0})
m2 = zeros(SMatrix{0, 3})
v = zeros(SVector{0}) # fine up to this point
m1 * m2 # ArgumentError: reducing over an empty collection is not allowed
m2 * m1 # fine
m1 * v # ArgumentError: reducing over an empty collection is not allowed
```

**Comment by andyferris** [comment]
Hmm... still getting errors from a different source. I didn't realize what was going on in cases 1 and 3...

Does this really make sense? I suppose that it is not harmful...

**Comment by andyferris** [comment]
OK should work now
