### ISSUE TITLE
Cross not implemented 

### ISSUE THREAD

**Issue by tkoolen** [andyferris/StaticArrays.jl#9]
Currently,
```julia
x = rand(SVector{3})
cross(x, x)
```
produces
```julia
3-element Array{Float64,1}:
 0.0
 0.0
 0.0
```
I would expect another `SVector`, which would require specializing `cross`.

See here for the Base implementation:
https://github.com/JuliaLang/julia/blob/master/base/linalg/generic.jl#L47

**Comment by andyferris** [comment]
Thanks for finding these gaps, @tkoolen. :)
